There are two ways of creating a `panic`; use the `panic!` macro explicitly or by taking an action that causes our program to panic (like accessing an array index that does not exist).
In both cases, Rust will print the error message, unwind, clean up the stack and quit. Using the `RUST_BACKTRACE=1` environment variable, we can get a backtrace of exactly what happened to cause the error.

In [main.rs](./projects/error_handling/src/main.rs), we try to access the 99th element of the vector. Running the program with
```
RUST_BACKTRACE=1 && cargo run
```
we get the following error
```
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 99', src/main.rs:3:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:162:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/slice/index.rs:261:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/slice/index.rs:19:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/vec/mod.rs:2691:9
   6: error_handling::main
             at ./src/main.rs:3:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

It tells us exactly what went wrong and where did it go wrong. If we disable the line, the code will be able to reach the line that explicitly calls `panic!` and we get an output like this

```
thread 'main' panicked at 'Crash and Burn', src/main.rs:2:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: error_handling::main
             at ./src/main.rs:2:5
   3: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

We can prevent Rust from unwinding and cleaning up memory by adding `panic = 'abort'` in the appropriate `profile` section of `Cargo.toml` file.

In our first example, where we are trying to access 99th element of the list when it does not exist, Rust panics and starts unwinding. In C, attempting to read beyond the end of a data structure is undefined behavior. We might get garbage values. This is called a _buffer overread_, which is a cause of many security vulnerabilities. 